name: Rust

run-name: Stargaze Environment

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v3
    - name: EnvSet
      run: export API_KEY_EX=222
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
